### ISSUE TITLE
CPU total temp

### ISSUE THREAD

**Issue by MithicSpirit** [SilverAzide/Gadgets#3] opened 2020-06-08 16:21 UTC
HWiNFO only reports a temperature for the entire CPU, rather than for each individual core (probably because my CPU doesn't have sensors for that). There should be an option for just having the total/average temperature for the entire CPU, instead of having it on a core-by-core basis.

**Comment by SilverAzide** [comment] 2020-06-09 02:00
Yeah, AMD CPUs don't have per-core temps.  Unfortunately, there's a couple issues, one is that the original addgadgets.com Sidebar Gadget displayed temps per core this way; and second, there's no place on the gadget to display a single value like this.

However, I suppose it would be cool to have a percentage bar just for the average/total temp, with 100% representing TjMax (assuming AMD reports that value).  Then the bar could show the percentage of TjMax, with the actual average/total temp to the right.  Both CoreTemp and HWiNFO plugins could do this...

Quite a lot of work tho...  ;-)  I have no way of running CoreTemp (or HWiNFO) on an AMD CPU to see what happens, either...

**Comment by DIGIN4** [comment] 2020-06-25 07:51
I have a Ryzen 7 3700X and the Clock on the widget shows 0 MHz, I checked HWiNFO and I couldn't find average clock anywhere for the whole CPU, is it possible to show it like Task Manager does? or Task Manager monitors a single core?

**Comment by SilverAzide** [comment] 2020-06-25 12:07
If the "Clock" value on the CPU Meter is showing 0 MHz, that almost always means you haven't configured it properly.  This value is the maximum of all your logical CPUs/threads when using HWiNFO.  OR, if not using HWiNFO, it is the speed reported by Rainmeter (i.e., Windows) or CoreTemp if you are using that.

There is no "average clock for the whole CPU" setting.  Task Manager shows what the CPU Meter shows, which is the maximum clock of all your cores, and they should match up fairly closely.  But showing zero means your HWiNFO config is bad.

**Comment by DIGIN4** [comment] 2020-06-25 12:30
"HWiNFO Shared Memory Viewer" shows 3 CPU [#0] listings, I tried all 3 Sensor IDs and still Clock shows 0 MHz, the RAM/page and core readings are working though.

**Comment by SilverAzide** [comment] 2020-06-25 14:53
The 3 "CPU [#0]" listings are for different things; I'm surprised you don't have more (I have 5).  One set is for clocks and voltages, one set is for temperature data, another set for power data, etc.  AMD CPUs are probably different, so you'll need to carefully review the data shown in the Shared Memory Viewer (SMV).  Don't just randomly try sensor IDs, that tells me you don't understand what you are seeing.  You need to find the exact Sensor ID, Instance ID, *and* Entry ID for your CPU core clocks and other settings.  There is only one right value, so carefully review the SMV and understand what you are configuring.  I tried to explain this in the include file as clearly as I could, but things are so different among manufacturers it is hard to be very specific.  I'm sorry I can't make things more clear, because it can be confusing.

**Comment by DIGIN4** [comment] 2020-06-25 15:27
I am using the correct Sensor ID, Instance ID, and Entry IDs:

![Annotation 2020-06-25 182524](https://user-images.githubusercontent.com/5035329/85749341-709ebe00-b711-11ea-9c4e-d5985e985464.jpg)

**Comment by SilverAzide** [comment] 2020-06-25 15:45
Excellent... that's one issue out of the way.  The next thing to check is Rainmeter.  Right-click the icon and open the About window.  Find the All CPU Meter skin and find the measures named [MeasureHWiNFOClockCore*N*]:

![Annotation 2020-06-25 113941](https://user-images.githubusercontent.com/2706567/85751650-c145f500-b6d8-11ea-981d-90e24c250e5c.png)

They should be active (not greyed out) and have non-zero values.  Should also see this near the bottom of the list of measures:

![Annotation 2020-06-25 114405](https://user-images.githubusercontent.com/2706567/85752269-44674b00-b6d9-11ea-9a93-6f484fe2ed2f.png)

Also look at the Log tab and make sure you don't see any errors.  You should see a line that says "HWiNFO detected.", but no errors.

**Comment by DIGIN4** [comment] 2020-06-25 15:57
The [MeasureHWiNFOClockCoreN] and the measures at the bottom are all greyed out.
I'm not seeing any errors or warnings, and "HWiNFO detected" is showing but next to (Gadgets\GPU Meter\GPU #1\GPU Meter.ini) only.

**Comment by SilverAzide** [comment] 2020-06-25 16:28
AHA!  That is a big indicator of the problem... so the CPU Meter isn't using anything, or at least it's not using HWiNFO.  Are you running CoreTemp or SpeedFan in addition to HWiNFO by any chance?

**Comment by DIGIN4** [comment] 2020-06-25 17:01
The only other monitoring software I'm running is MSI Afterburner. (just installed it and nothing changed)
All the [CalcIs____InUse] are greyed out, including CalcNoTempInUse.

I changed all the DTS to point to the CPU average Temp, still Clock shows 0 MHz.
![Annotation 2020-06-25 195743](https://user-images.githubusercontent.com/5035329/85765060-6e8f2c00-b71e-11ea-9423-449405646be0.jpg)

The temps were never shown on the gadget itself, even after modifying the config file:
![Annotation 2020-06-25 200027](https://user-images.githubusercontent.com/5035329/85765156-86ff4680-b71e-11ea-9742-e9caa4e27258.jpg)

**Comment by SilverAzide** [comment] 2020-06-25 17:23
Ah, I see the issue.  Open the CPU Meter Settings and CHECK the option "Show Core Temperatures".  It must be unchecked now.

**Comment by DIGIN4** [comment] 2020-06-25 17:27
That's it! Clock is showing now, thank you!

**Comment by SilverAzide** [comment] 2020-06-25 17:33
OK, Great!  However, there is still a problem.  You are the second person with an AMD CPU who has mentioned that the clock is showing "0 MHz" and is NOT using any monitoring software (your HWiNFO setup was being ignored until you checked that option).  The way you were configured (before checking the "show temps" option) should have shown the CPU clock as reported by Rainmeter, which reports the value given by Windows.  It appears there might be a bug someplace in Rainmeter.  You should not need any monitoring stuff for the CPU Meter UNLESS you want to show temperatures, OR you want to show the "true" clock speed of the cores (including boost speeds).

I will post this issue on the Rainmeter forums, but unfortunately I have no way to test this as I don't own any gear with an AMD CPU.  :-(

**Comment by SilverAzide** [comment] 2020-06-25 17:38
> That's it! Clock is showing now, thank you!

Can you open the About > Skins tab and tell me what the value of the [MeasureCPUSpeed] measure is?  It should be near the top and not greyed out.  This is supposed to be your base clock as reported by Rainmeter (it will not reflect boost speeds).

**Comment by DIGIN4** [comment] 2020-06-25 17:54
![Annotation 2020-06-25 205433](https://user-images.githubusercontent.com/5035329/85773023-1825eb80-b726-11ea-9e6b-73a12f650574.jpg)

**Comment by DIGIN4** [comment] 2020-06-25 17:58
I can test for you, once you open a thread on Rainmeter's forum send me a link.

**Comment by SilverAzide** [comment] 2020-06-25 18:00
THANK YOU!  I've posted this issue on the Rainmeter bug forum here:  https://forum.rainmeter.net/viewtopic.php?f=14&t=35577

Another user contacted me with this issue, he was using a Ryzen 9 3950X, and had the exact problem.  If you go to the About > Version tab, can you click the "Copy to clipboard" and post the results here or on the Forum?  You can sanitize the data to remove your username if you want.

**Comment by DIGIN4** [comment] 2020-06-25 18:03
Rainmeter 4.3.1.3321 (64-bit)
Language: English (1033)
Build time: 2019-09-22  7:26:11
Commit Hash: 0ba4dfc4
Windows 10 Pro 1909 64-bit (build 18363) - English (1033)
Path: C:\Program Files\Rainmeter\
SkinPath: C:\Users\net_b\Documents\Rainmeter\Skins\
SettingsPath: C:\Users\net_b\AppData\Roaming\Rainmeter\
IniFile: C:\Users\net_b\AppData\Roaming\Rainmeter\Rainmeter.ini

**Comment by SilverAzide** [comment] 2020-06-25 18:04
Perfect!  I'm using the same versions of everything as you are...  I appreciate it!

**Comment by SilverAzide** [comment] 2020-06-25 19:10
> I can test for you, once you open a thread on Rainmeter's forum send me a link.

It has been suggested you try this procedure -- [HOW TO: Fix your Performance Counters database](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Fix-your-Performance-Counters-database)

After doing this, exit HWiNFO and see if your clock speed reports zero again.  You should not need to refresh or anything, the Gadget should auto-detect things.

**Comment by DIGIN4** [comment] 2020-06-25 19:58
I followed the steps then exited HWiNFO and the Clock is showing 0 MHz

**Comment by SilverAzide** [comment] 2020-06-25 20:07
Well, dang.... It was worth a shot, anyway.  I'll have to some up with a work-around.  One of the devs is saying he can't reproduce it, so I'm not sure what else I can do.  :(

**Comment by SilverAzide** [comment] 2020-06-27 03:04
> I followed the steps then exited HWiNFO and the Clock is showing 0 MHz

Hello DIGIN4!  Would you be willing to do more testing on this topic.  The main Rainmeter developer, Brian, has responded to your issue and has created a special beta version for you.  You can check out his reply here: https://forum.rainmeter.net/viewtopic.php?f=14&t=35577&start=10#p179303.

If you can install the Rainmeter 4.4 beta version and give the CPU Meter another try, we'd appreciate it.  v4.4 is actually pretty stable, so you can upgrade to it and keep it, or uninstall it after testing if you want to stay on the official release.  The Gadgets are already tested on v4.4 beta and are working fine.  All you need to do is install, and NOT run HWiNFO for this test.  Check the CPU Meter clock speed and see if it is still returning zero.  Also check the log and if you find any debug info paste everything here or on the forum.

Thank you!

**Comment by DIGIN4** [comment] 2020-06-27 06:28
Hello!
I installed the beta version and Clock is showing 0 still when HWiNFO isn't running, no errors in log, here's a screenshot:

![Annotation 2020-06-27 092635](https://user-images.githubusercontent.com/5035329/85916318-6804cf80-b858-11ea-8432-94b478da835f.jpg)

**Comment by brianferguson** [comment] 2020-06-27 15:04
Thank you for testing this version. Unfortunately, it appears that there is a bug with the Windows API function [CallNtPowerInformation](https://docs.microsoft.com/en-us/windows/win32/api/powerbase/nf-powerbase-callntpowerinformation) - at least for some CPU's.

It could simply be a driver error, or an error on the Windows side. Hopefully this will get fixed on the next Windows update. When you get the Windows May 2020 (2004) update, could you test it one more time?

In the meantime, I would continue to use the HWiNFO solution.

Thank you for testing!
-Brian

**Comment by DIGIN4** [comment] 2020-06-27 15:43
> When you get the Windows May 2020 (2004) update, could you test it one more time?

Will do and report back.

Thank you for your help and for the awesome gadgets!

**Comment by DIGIN4** [comment] 2020-08-01 15:00
> For some reason, it is reporting a successful query, but the result is still 0. It could simply be a driver error, or an error on the Windows side. Hopefully this will get fixed on the next Windows update. When you get the Windows May 2020 (2004) update, could you test it one more time?

Hi, I upgraded to Windows 10 2004 version and when I quit HWiNFO Clock shows 0 (temperature and fan speed also stops showing), this is on my AMD 3700X CPU with latest drivers.

I also upgraded to Windows 10 2004 on my laptop which has Intel i5-8250U and same issue is happening on it too. 

Using Rainmeter 4.3.1 and Gadgets v5.5.0

**Comment by SilverAzide** [comment] 2020-08-02 15:23
Hm, interesting.  Part of this might be a glitch where the code is not detecting HWiNFO has ended and thus not switching back to the default measures that just use Rainmeter.  With regard to the fan, the fan speed _should_ go to zero when HWiNFO terminates, because that is the source of the data.  Rainmeter itself can't show fan stuff.  The gadget does not automagically adjust itself to hide the fan entry, though that would be sort of cool if it did.  But the clock should not show zero, that's a definite problem.  I cannot reproduce this behavior, unfortunately.

Take a look at the log.  You should see entries like "No temperature monitor detected" and "HWiNFO detected" showing up.  You can start and stop HWiNFO and see the skin detecting this and switching back and forth from Rainmeter to HWiNFO and back again.  If you don't see anything in the log, then perhaps the measures that detect which 3rd-party utility is active aren't working quite right.  As I say, they are fine for me.  In the About dialog Skins tab, take a look at the MeasureCPUSpeed measure (and the two above it) and make sure none of them are showing zero.  v5.5.0 should never show zero, as far as I know, but I don't have an AMD machine to verify.

**Comment by DIGIN4** [comment] 2020-08-02 15:46
On AMD 3700X CPU:

When I quit HWiNFO:

![Annotation 2020-08-02 183107](https://user-images.githubusercontent.com/5035329/89126458-806aa880-d4ee-11ea-99a9-0a696881a78a.jpg)

When I start HWiNFO again:

![2Annotation 2020-08-02 183107](https://user-images.githubusercontent.com/5035329/89126498-abed9300-d4ee-11ea-88f3-90c9c4af8a80.jpg)

From About > Skins tab (when HWiNFO is running/closed on the AMD 3700X CPU ):

![3Annotation 2020-08-02 183548](https://user-images.githubusercontent.com/5035329/89126549-0e469380-d4ef-11ea-9eb7-b42364b762fe.jpg)

On the Intel i5-8250U is now showing clock when I quit HWiNFO for some reason, Log tab shows "No temperature monitor detected" warning only, but the MeasureCPUSpeed is NOT 0, when I run HWiNFO again it shows "HWiNFO detected"

**Comment by SilverAzide** [comment] 2020-08-02 16:36
Interesting.  It appears the problem is the MeasureCPUFrequency measure; it should never be zero, unless (as I recently learned) you are running Windows 7.  Win 10 should be fine tho.  I made a change to the skin after v5.5.0 was released, so try the following:

* Right-click the CPU Meter skin and select "Edit skin" from the menu.
* Find the chunk of code with the three measures MeasureCPUFrequency, MeasureCPUPercentPerformance, and MeasureCPUSpeed (they are all together).
* Replace these 3 measures with the following code:

```
[MeasureCPUFrequency]
Measure=Registry
RegHKey=HKEY_LOCAL_MACHINE
RegKey=HARDWARE\DESCRIPTION\System\CentralProcessor\0
RegValue=~MHz

[MeasureCPUPercentPerformance]
Measure=Plugin
Plugin=UsageMonitor
Category="Processor Information"
Counter="% Processor Performance"
Name="0,_Total"

[MeasureCPUSpeed]
Measure=Calc
Formula=MeasureCPUFrequency * (MeasureCPUPercentPerformance ? MeasureCPUPercentPerformance : 100) / 100
```

Let me know if this resolves your issue.  The source of the problem appears to be that certain AMD CPUs are not properly reporting their frequency to Windows.  I've discussed this with a couple of the Rainmeter developers and it is not something they can fix, it is a glitch with AMD that has to be worked-around.

**Comment by DIGIN4** [comment] 2020-08-02 16:50
The new code resolved the issue! now Clock is showing the correct number when HWiNFO is closed, and in Rainmeter > About > Skins it's not showing 0 any longer for MeasureCPUSpeed, MeasureCPUPercentPerformance, and MeasureCPUFrequency.

Thank you!

**Comment by SilverAzide** [comment] 2020-08-02 17:41
Sweet!  Now it looks like I gotta release an update to the Gadgets sooner than I'd hoped.  There's going to be a minor fix to the weather skin soon anyway according to the Rainmeter dev working on it, so I'll wait for that.

**Comment by SilverAzide** [comment] 2020-10-24 15:37
This enhancement will be in the next release.  In the Settings, a new option "Show Temperatures Per-Core" (default is checked) can be UNchecked by AMD users or by anyone who wants to see only a single temperature (CoreMax) instead of per-core temps.

![All CPU Meter SingleTemp](https://user-images.githubusercontent.com/2706567/97085688-ff064c00-15ec-11eb-832f-283f4db56769.png)

**Comment by johny-mnemonic** [comment] 2021-04-07 21:49
@SilverAzide Thanks for the new version with this new feature!
I just upgraded to v6.0.0 and it works in the regard that it shows the temperature on the new line as your picture shows.
But even though I have checked "Override TjMax", the percentage in last column is 0%.

Also I would much rather see a name i.e. "Temp" in the middle column (like all other lines) and the temperature in the last column, using only the bar in first column to show how close the temperature is to the TjMax.

**Comment by SilverAzide** [comment] 2021-04-08 00:36
> But even though I have checked "Override TjMax", the percentage in last column is 0%.

I cannot duplicate this behavior, but I _think_ I see the possible solution.  The only confusion is why can't I see what you are seeing.  Weird.  In any case, I am going to assume you are using HWiNFO.  If so, edit the skin and find the measure `[CalcHWiNFOPercentTjMax]`.  Add the following lines:

``` ini
MinValue=0
MaxValue=1
```
If you are using CoreTemp or SpeedFan, there are two other measures (`[Calc___PercentTjMax]`) that need fixing similarly.  I will add this fix into the next release.  Thanks for catching this!

**Comment by SilverAzide** [comment] 2021-04-08 00:41
> Also I would much rather see a name i.e. "Temp" in the middle column (like all other lines) and the temperature in the last column, using only the bar in first column to show how close the temperature is to the TjMax.

I debated doing this as well, but I went with the logic that everything in the right-most column are percentages.  This would be the only temperature.  But I'm not super-happy with the current appearance either (especially when TjMax = 100), so I will try your suggestion for the next release.  👍

**Comment by johny-mnemonic** [comment] 2021-04-08 17:50
I can confirm, that it definitely has something to do with running this on AMD, as on my Intel laptop it works fine.
Looks like the TjMax Override simply doesn't work when there is no TjMax value to override. Maybe simply setting it to 0 and not blank would make it work.

**Comment by SilverAzide** [comment] 2021-04-08 21:00
OK, thanks for confirming!  Are you still having this issue after making the change to add the MinValue/MaxValue lines above?

If so, when the "Override TjMax" option is checked, the TjMax value is taken from the value entered, which is 100 by default (i.e., it is not taken from any sensor reading).  At that point the calculation simply the value from the "CPU(Tdie)" sensor divided by 100 (or whatever the TjMax value is set to).  Are you seeing a  non-zero value from the `CalcHWiNFOPercentTjMax` measure? Can you confirm that you have the HWiNFO_CPU0_DTS_CoreMax variable set to the "CPU(Tdie)" sensor index?  This variable can't be left blank in the config.  If all is OK, then you should be seeing a non-zero percentage (I hope!).

**Comment by johny-mnemonic** [comment] 2021-04-08 21:13
No, adding the Min/Max values didn't help.
I have added those values like this:
```
[CalcHWiNFOPercentTjMax]
MinValue=0
MaxValue=1
Measure=Calc
~~~
```

I have these configured:
```
HWiNFO_CPU0_DTS_Core0Temp=6
HWiNFO_CPU0_DTS_CoreMax=6
```
So both points to `CPU [#0]: AMD Ryzen 5 1600: Enhanced     CPU (Tctl/Tdie)` of HWinfo.
And I have Override TjMax set to 95. I also tried 50 to see whether anything will change, but still constant "0%".

**Comment by SilverAzide** [comment] 2021-04-08 21:37
AHA!  Found the bug!  **THANKS!***  I'll post a fix here something shortly if it is simple, otherwise I'll release a new version.  Hopefully it is simple...

**Comment by SilverAzide** [comment] 2021-04-09 02:08
OK, this is not a simple fix, and the CoreTemp logic is glitched too.  I'll have to release a new version.  😞
Here's a chance to try the new Update Checker gadget!  Hopefully it won't blow up like everything else... (The Update Checker only checks once per 12 hours; first when the gadget loads, then every 12 hours thereafter.)

**Comment by SilverAzide** [comment] 2021-04-09 23:26
Corrected in v6.0.1.

**Closed by SilverAzide** 2021-04-09 23:26 UTC
Labels: bug

**Comment by johny-mnemonic** [comment] 2021-04-10 23:37
Not sure, how the Update Checker should work, but I have waited 24 hours after release and I got no announcement about new version. I tried opening the Welcome gadget, disable update check and enable it again and then I got the update announcement.
Another thing might be, that the PC have to be running at the exact time of the update check. In case there is no logic that would do the check after the PC wakes-up from the sleep after the scheduled check should have run and execute it, than this also explains it.

Anyway, update itself went smooth and everything seems to be working🎉Thanks!

**Comment by SilverAzide** [comment] 2021-04-11 01:26
Oh yes, you are probably right.  The skin runs the check at the time the skin loads, then it checks at 12 hour intervals.  If the machine is sleeping or something, then the time is missed (i.e., WebParser fails), then it's another 12 hours... etc.  I guess I can make it fancier and record the time of the last check and fire the check if it's 12+ hours difference.  That way the skin will react once the PC wakes up.  Or I could just set to time interval to something shorter, like 3 hours.  Something for the next version!  😃

**Comment by johny-mnemonic** [comment] 2021-04-11 06:59
Yep, that explains it.
I guess improving this is just nice to have, nothing important.
Thanks again for your work on this project!
