### ISSUE TITLE
Incorrect Clock Frequency

### ISSUE THREAD

**Issue by driscoll42** [SilverAzide/Gadgets#114] opened 2024-10-31 19:29 UTC
I have an Intel Core Ultra 7 155U which has a max turbo frequency of 4.8 GHz, however on CPU Meter it'll report frequencies much higher, sometimes 7.1+ GHz, an example below of it in the 6 GHz range. I suspect this is due to the core configuration of Performance-Efficient-Low Power cores.

![image](https://github.com/user-attachments/assets/8b93709f-e9f2-4bc0-9ad7-efd9a82a65b4)

However it could also be due to my permissions, I'm on a work laptop so I don't have admin rights and can't run HWInfo to verify

**Comment by SilverAzide** [comment] 2024-11-02 00:33
Hello!  Sorry to hear you are having issues.  You very well may be correct that this is caused by the LP cores.  You are the first person to contact me with a CPU that has a CPU with P-E-LP cores.

The core clock speed you are seeing is calculated and displayed 3 different ways.

- If you were using HWiNFO (which I understand you are **_not_**), the clock is simply the maximum clock of all cores.  This is the most accurate and straightforward option.
- If you were using CoreTemp, it has an option which returns the current max clock speed.  I don't know how it calculates this on hybrid CPUs, but I believe it is similar to HWiNFO (i.e., the max of all cores).
- If you are using plain ol' Rainmeter with no third-party plugins (which is your situation), there is no simple way to get this value.  The clock speed has to be calculated by getting the base clock (from the registry) and multiplying that by the "% processor performance" coming from PerfMon.  This seemed pretty reliable until now...

Your CPU cores have different base clocks for each core type.  Your P cores can do 282% of their base clock speed in turbo mode, LP cores can go 300% over, and your E cores can do 317% over.  Your "base clock" in the registry is probably the base of the fastest P cores (~1700 MHz), so I'm thinking the calculation is being thrown off.  1700 * 317% is 5400, which is way beyond the 4800 max of your CPU.  (Not sure how you are seeing 6-7+ GHz speeds, but perhaps the data is off even worse.)  I may have to go back to the drawing board for these newer hybrid CPUs.

If you can, please open the Rainmeter About windows and on the Skins tab, select the All CPU Meter skin, and post a screenshot of the following measures:
![image](https://github.com/user-attachments/assets/8e5582cb-e67f-4a4c-ad28-da6c5af5b4af)

I'm interested in seeing your base frequency and the percent performance.  If you can grab the image when it it showing some impossible value (i.e., >5 GHz), that would be nice.  In the meantime, I will check to see if I can come up with a more accurate way to get the max clock speed using PerfMon.

**Comment by driscoll42** [comment] 2024-11-02 16:16
![image](https://github.com/user-attachments/assets/0f827db0-6093-4a3f-91c7-0456a867a69d)

Here's a screenshot of those values with a 5+ GHz value without using any plugins. I did notice in my attempts to force load on the CPU (using CPU-Z) that in multithread use, the frequencies seem reasonable, ~3 GHz, it's the singlethreaded loads that shoot up to 5+ GHz.

Unfortunately I did try Core Temp and it requires admin permissions. On my personal desktop I use HWiNFO since I have admin. If this is a case where it's just not possible to get accurate readings without having admin rights, that'd make sense. I know my use case of using this on a machine where I lack admin rights is a corner case.

Regardless, thank you for all your hard work on these gadgets, been using and loving them for years!

**Comment by driscoll42** [comment] 2024-11-02 16:56
From that screenshot, I can see how the 2.688 *2.82 would give a max frequency of 7.58 GHz, which fits some of the random data I've seen. As you mentioned, looking at [Intel Ark](https://ark.intel.com/content/www/us/en/ark/products/237327/intel-core-ultra-7-processor-155u-12m-cache-up-to-4-80-ghz.html) the Performance base frequency should be 1.7 GHz. This reminded me that I did see 2.688 GHz over in CPU-Z, screenshot below (technically 2688.22 MHz)

![image](https://github.com/user-attachments/assets/8f3f2234-e1dc-4c47-8b9d-b95d2933a615)

So it doesn't seem to be a All Core specific bug, CPU-Z is at least getting the same data.

**Comment by SilverAzide** [comment] 2024-11-02 17:18
Very interesting!  I've been looking at that too.  So I no clue where that 2688 MHz is coming from; that is the reason for the goofed up clock speed calculation.

I tweaked the CPU Meter to alter the clock speed calc method, although after seeing your posts I'm not sure it will help.  PerfMon can tell me the base clock of each core, plus the percentage performance of each core.  In theory, if I multiply these together I'll get the actual clock speed, though from looking at my CPU (Core i9 12950HX) it is not as accurate as I would hope.  Running a CPU stress test does get the cores hitting roughly the same values that HWiNFO reports.  The E-cores on my CPU are the same base clock as the P-cores, so I'm not sure if this is an apples-to-apples comparison to your situation.

If you can copy the skin file from the attached zip over your existing file (`\Rainmeter\Skins\Gadgets\All CPU Meter\CpuMain.inc`).  Make a backup if you want.  Refresh the skin and see if the CPU speed appears reasonable.

I don't really like the way I had to fix this because it required adding 128 more PerfMon measures to a skin that is already wildly complicated.  But if it works for you, that would be great.  I am not too hopeful, given the weirdly reported base clock of your system.

[CpuMain.zip](https://github.com/user-attachments/files/17607772/CpuMain.zip)

P.S.:  It's very interesting to see that your P-cores are not contiguous on the CPU chip.  Threads 0/1 and 10/11 are your P cores.  I've never seen them split up like that.  Interesting.

**Comment by driscoll42** [comment] 2024-11-02 21:47
![image](https://github.com/user-attachments/assets/8347bd6e-6a8f-42e6-93f7-57dba92acb9f)

That seems to have fixed it! I don't see the frequency ever going beyond 4.7 GHz. Ran a Cinebench SP and MP test, and the frequency seemed consistent with what I should be seeing. Can't really speak to how accurate it is, but feels accurate.

I was wondering how to identify which cores were the P-Cores, thanks for helping me figure that out. Any way to tell you know of which are the LP cores?

**Comment by SilverAzide** [comment] 2024-11-02 22:35
Great news!  I'll add this into the next release of the Gadgets.  Thanks a bunch for testing this for me.

I don't know how to test for the LP cores, but if I had to guess, since there are two of them, they are the last two (12/13, or 13/14 if you count starting from 1).  The CPU Meter can really only see "hyperthreaded vs. single-threaded"; check the measure named `MeasureCPULogicalToPhysicalCoreMap`:

![image](https://github.com/user-attachments/assets/244f03f8-fed4-42d4-a876-1ee7dfe13a54)

In your case you can see a pair of 2 logical cores (your first P-core), then the 6 single-threaded E-cores, another hyperthreaded P-core, and the 2 LP-cores at the end.  I think these new Intel chips use multiple "chiplets" instead of one big chip, so perhaps that's the reason.

**Comment by driscoll42** [comment] 2024-11-03 16:41
The MeasureClockCPU does clearly show the LP cores in 13/14 with the 700 MHz clock, thank you again! 

![image](https://github.com/user-attachments/assets/7074f470-fcce-4afe-b819-4b96724daee7)

**Comment by driscoll42** [comment] 2024-11-03 17:16
A thought I had this morning, it could be useful to update the text for these kinds of CPUs to P-Core 1, P-Core 2, E-Core 3, E-Core 4, LP-Core-13, etc.... based on their frequency. But that might add to much complexity and it's not like there's a ton of horizontal space in the gadget right now.

**Comment by SilverAzide** [comment] 2024-11-03 18:04
This is really cool!  I couldn't see this on my machine because my base clocks are all the same.  Thanks a bunch for letting me know!

But it's still an even bigger mystery where that 2688 number is coming from, LOL.  It's not an average, a sum, a max, a min, or any multiple of anything I can see.

As far as identifying the core types, I don't really have a reliable way to detect this.  There's been other folks asking about adding this feature as well. All I know for sure is core clock speeds and whether they are hyperthreaded.  I think read someplace that some Intel CPUs even have single-threaded P cores now?? In any case, you are right, the space is really cramped anyway, even if I could tell which ones are which.

For your question about the measures, in general I only enable the needed ones; e.g., for your 14 logical cores, only 14 of the 64 possible measures (per thing being measured) are enabled.  My Rainmeter usage stays below 1% typically when the machine is idle, and I'm using at least 9 gadgets all the time.  The Drives Meter is probably the biggest hit due to how many measures it takes to monitor a single drive, so uncheck as many drives from monitoring as practical for your machine.   The test CPU skin I sent you will not disable the clock speed measures if you are using HWiNFO; that will be part of the final release, so you'll have 28 or so measures "measuring" for no reason.  I figure that would be OK for your work machine.  For your personal machine, I'd stick with HWiNFO and the original skin.

**Comment by driscoll42** [comment] 2024-11-04 19:08
I was curious, and did a bit of looking, and from the validations on CPU-Z for my CPU:

https://valid.x86.fr/292uh5
https://valid.x86.fr/b1t547
https://valid.x86.fr/bara0t
https://valid.x86.fr/7r6m4d
https://valid.x86.fr/d7uuix

My best guess of the 2688 is that it's taking the 4-48 multiplier range and averaging it as (4+48=52 /2 = 26), which is close to a Bus Speed of 99.55 * 27 that'd get to 2688. I'm grasping a bit here, but it's the closest to the data I see. I imagine it's an issue with the lack of admin permissions ultimately. 

Yeah, you could probably figure it out in my case, but the maintenance of every single edge case would be... daunting I expect. Once one figures it out, just need to know where to look.

And fantastic, yes, using HWIiNFO at home, just using this one for the work machine. It's fine to have a few extras monitoring for no reason, not causing many issues. I was more wondering if there were a few hundred extra ones monitoring for no reason. 

Regardless, again thank you for all your work!

**Comment by SilverAzide** [comment] 2024-12-01 00:46
Corrected in next release.

**Closed by SilverAzide** 2024-12-01 00:46 UTC
Labels: bug, enhancement
