### ISSUE TITLE
Suggestion about merging Top CPU Meter into CPU and RAM 

### ISSUE THREAD

**Issue by anhell** [SilverAzide/Gadgets#97] opened 2024-04-07 10:12 UTC
Sorry, I don't know if this is the correct place or even if you are accepting suggestions, but I'm using the Gadgets and I really like the Top Process Meter, specially the Top CPU one, because it shows both RAM and CPU, but I think it's would be cool if for each meter update, or a couple of updates, it could swap from only showing CPU and then only showing RAM, that way we can narrow 2 very useful meters in one (maybe go the extra mile and make it cycle among all top process meters you choose, but I think RAM and CPU are the essential ones). I could make it hide and show both every couple of seconds, but even showing only RAM it would still be ordered buy CPU percentage, I'm not skilled enough to be solving that part, so that's my suggestion.

**Comment by SilverAzide** [comment] 2024-04-07 15:49
Hello!  Glad you are enjoying the Gadgets!

I'm not sure about merging them together, as they are showing different things. It would be quite messy in the code to have the skin alternate views from one to the other.  All I can do is suggest alternatives; for example, you can use the CPU Meter's feature to show the top 5 processes by CPU, then position the Top RAM meter underneath to show the top N by RAM.

Another trick you could do, very similar to your idea, is to create an invisible "controller" skin.  All this skin would do is show and hide the other skins.  You could position the Top N skins on top of each other, then have them fade in and out in a round-robin cycle every few seconds.  (You'd use !ShowFade and !HideFade bangs to do this if you wanted a nice fade effect.)  All you need for a skin like this is a Time or Loop measure to control the cycle time, plus a few variables to keep track of things and you are done.  Easy-peasy!  😄 

Ordering your Top RAM by CPU usage won't give you the results you are expecting, I'm afraid.  (I've already tried it.)  The problem is that, for some very annoying reason I don't understand, the Rainmeter measures will not return any data if the percentage CPU is less than 0.1%.  This is why the Top CPU skin isn't completely filled, and bounces around with different numbers of items.  I don't like this, but there is nothing that I can do about it.  😞 

Anyway, I agree, both skins are very handy to have showing at the same time.  If you'd like to try building a controller skin, got for it.  If you need help, you can post questions here.  I'd suggest reading through the Rainmeter manual:

[Skins](https://docs.rainmeter.net/manual/skins/)
[Skin bangs](https://docs.rainmeter.net/manual/bangs/#Skin)
[Loop measure](https://docs.rainmeter.net/manual/measures/loop/)
[Time measure](https://docs.rainmeter.net/manual/measures/time/)

The Rainmeter Manage app even has a way to help you get started.  Just right-click the Gadgets folder (or better yet, the Top Process folder), and add your own folder underneath, like so:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/4fa328ea-abf9-4e3b-b38b-517b15f50def)

**Comment by SilverAzide** [comment] 2024-04-13 16:00
Closing this issue for now; will reopen later if OP responds.

**Closed by SilverAzide** 2024-04-13 16:00 UTC
